$ErrorActionPreference = "Stop"

$Root = (Resolve-Path ".").Path
$Deployment = "delta-local-app-dev"
$Container = "delta-local-app-dev"

Write-Host "Delta Kubernetes source sync"
Write-Host "Source: $Root"
Write-Host "Press Ctrl+C to stop."
Write-Host ""

# Files/directories that should never be synchronized.
$Excluded = @(
    ".git",
    "node_modules",
    "uploads",
    "build",
    "dist",
    "coverage",
    ".cache",
    ".react-router"
)

# Remember recently processed files to avoid duplicate
# FileSystemWatcher events generated by a single save.
$LastSync = @{}

function Should-Ignore($relativePath) {
    $parts = $relativePath -split '[\\/]'

    foreach ($part in $parts) {
        if ($Excluded -contains $part) {
            return $true
        }
    }

    return $false
}

function Get-DevPod {
    Write-Host "Waiting for Delta development Pod..."

    while ($true) {
        $pod = kubectl get pods `
            -l app=$Deployment `
            --field-selector=status.phase=Running `
            -o jsonpath='{.items[0].metadata.name}' 2>$null

        if ($pod) {
            # Make sure the application container is actually available
            # before returning it.
            kubectl exec $pod -c $Container -- true 2>$null

            if ($LASTEXITCODE -eq 0) {
                return $pod
            }
        }

        Start-Sleep -Seconds 2
    }
}

function Sync-File($fullPath) {
    if (-not (Test-Path $fullPath -PathType Leaf)) {
        return
    }

    $relativePath = $fullPath.Substring($Root.Length)
    $relativePath = $relativePath.TrimStart([char[]]"\/")

    if (Should-Ignore $relativePath) {
        return
    }

    # Debounce duplicate filesystem events.
    $now = Get-Date

    if ($LastSync.ContainsKey($relativePath)) {
        if (($now - $LastSync[$relativePath]).TotalSeconds -lt 2) {
            return
        }
    }

    $LastSync[$relativePath] = $now

    $pod = Get-DevPod

    # Kubernetes/Linux paths always use forward slashes.
    $remotePath = $relativePath.Replace("\", "/")
    $remoteDirectory = [IO.Path]::GetDirectoryName($remotePath).Replace("\", "/")

    if ($remoteDirectory) {
    kubectl exec $pod -c $Container -- `
        mkdir -p "/delta/$remoteDirectory"
    }

    Write-Host "SYNC: $relativePath"

    cmd /c "kubectl exec -i $pod -c $Container -- sh -c ""cat > '/delta/$remotePath'"" < ""$fullPath"""

    if ($LASTEXITCODE -ne 0) {
        Write-Warning "Failed to sync: $relativePath"
    }
}

function Sync-AllSource {
    $pod = Get-DevPod

    Write-Host "Initial source sync to Pod: $pod"
    Write-Host "This may take a little while..."

    # Stream the repository as a tar archive directly into the Pod.
    # Exclude files/directories that belong to the workstation or
    # are managed separately inside Kubernetes.
    cmd /c "tar --exclude=.git --exclude=node_modules --exclude=uploads --exclude=build --exclude=dist --exclude=coverage --exclude=.cache --exclude=.react-router -cf - . | kubectl exec -i $pod -c $Container -- tar -xf - -C /delta"

    if ($LASTEXITCODE -ne 0) {
        throw "Initial source synchronization failed."
    }

    Write-Host "Initial source sync complete."
    Write-Host ""
}

$pod = Get-DevPod

$sourceExists = kubectl exec $pod -c $Container -- sh -c "test -f /delta/package.json && echo yes || echo no"

if ($sourceExists -eq "yes") {
    Write-Host "Source already present in Pod - skipping initial sync."
    Write-Host ""
}
else {
    Sync-AllSource
}

$Watcher = New-Object IO.FileSystemWatcher
$Watcher.Path = $Root
$Watcher.IncludeSubdirectories = $true
$Watcher.NotifyFilter = [IO.NotifyFilters]'FileName, LastWrite'
$Watcher.EnableRaisingEvents = $true

Register-ObjectEvent $Watcher Changed -SourceIdentifier "DeltaChanged" | Out-Null
Register-ObjectEvent $Watcher Created -SourceIdentifier "DeltaCreated" | Out-Null

Write-Host "Watching for source changes..."

try {
    while ($true) {
        $event = Wait-Event -Timeout 1

        if ($event) {
            $fullPath = $event.SourceEventArgs.FullPath
            Remove-Event -EventIdentifier $event.EventIdentifier

            Sync-File $fullPath
        }
    }
}
finally {
    $Watcher.Dispose()
    Get-EventSubscriber | Unregister-Event
}