apiVersion: v1
kind: Secret

metadata:
  name: delta-local-app-secret

type: Opaque

stringData:
  DATABASE_URL: "postgresql://postgres:postgres@delta-local-db:5432/dts-shared-01"
  SESSION_SECRET: "not-random-dev-secret"
